/**********************************************************************************************************************
 * \file PMS_Power_Down_Standby.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "PMS_Power_Down_Standby.h"
#include "IfxPort.h"
#include "IfxScuWdt.h"
#include "IfxPms_reg.h"
#include "Bsp.h"
#include "SCR.h"
#include "Ifx_Types.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED_1           &MODULE_P00,5                   /* LED: Port, Pin definition     */
#define LED_2           &MODULE_P00,6                   /* LED: Port, Pin definition     */
#define Push_Button     &MODULE_P00,7                   /* Input: Port, Pin definition   */
#define WAIT_TIME       500                             /* Wait time constant in milliseconds   */

#define LED_D110                            &MODULE_P13,3   /* LED that signals the start of the application        */
#define LED_D107                            &MODULE_P13,0   /* LED that signals the entering in Standby mode        */

#define TICKS_TO_WAIT                       0x8000000       /* Total amount of ticks in approximately one second    */
#define MASK_BIT2_TO_8_ONES                 0x1FC           /* Mask to clear all Standby and Wake-up flags          */
#define WAKEUP_PINA_ENABLE                  0x1

#define WAKEUP_ON_VEXT_RAMPUP_ENABLE        0x1
#define WAKEUP_ON_VEXT_RAMPUP_DISABLE        0x0

#define WAKEUP_PORST_ENABLE                 0x1
#define WAKEUP_PORST_DISABLE                 0x0


#define WAKEUP_SCR_ENABLE                   0x1
#define TRIGGER_ON_ANY_EDGE                 0x3             /* Bits to configure the wake-up trigger on any edge    */

#define DISABLE_WAKEUP_ON_ESR0              0x0

#define REQUEST_STANDBY                     0x3             /* Standby Mode request bits for the system             */

#define DISABLE_WAKEUP_ON_PORST             0x0
#define DISABLE_WAKEUP_ON_PINA              0x0
#define DO_NOT_TRIGGER_ON_ANY_EDGE          0x0

#define STANDBY_RAM_IS_SUPPLIED             0x2             /* Standby RAM (CPU0 dLMU RAM) is supplied.*/

#define BLANKING_FILTER_DELAY_FOR_WAKE_UP   0x2;

volatile unsigned int pin_status;


/*********************************************************************************************************************/
/*------------------------------------------------Function Implementations-------------------------------------------*/
/*********************************************************************************************************************/
/* This function configure the LEDs */
void initLEDs(void)
{
    /* Set Port Pin 13.3 and 13.0 to output mode */
    IfxPort_setPinModeOutput(LED_D110, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LED_D107, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}

/* This function put the system into Standby after a few seconds */
void runStandby(void)
{
    IfxPort_setPinLow(LED_D110);                                          /* Set Port Pin 13.3 to high - D110 on    */
    IfxPort_setPinHigh(LED_D107);                                         /* Set Port Pin 13.0 to high - D107 off   */

    for(uint32 i = 4 * TICKS_TO_WAIT; i > 0; i--);                        /* Wait for ~4s                           */

    IfxPort_setPinLow(LED_D107);                                          /* Set Port Pin 13.0 to high - D107 on    */

    for(uint32 i = TICKS_TO_WAIT; i > 0; i--);                            /* Wait for ~1s                           */

    stepIntoStandbyMode();                                                /* Put the system into Standby            */
}

/* This function put the system into Standby */
void stepIntoStandbyMode(void)
{
    IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());  /* Clear Safety EndInit protection        */
    IfxScuWdt_clearCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());        /* Clear CPU EndInit protection           */

    MODULE_PMS.PMSWSTATCLR.U = MASK_BIT2_TO_8_ONES;                       /* Clear all Standby and Wake-up flags    */

    Ifx_PMS_PMSWCR0 pmswcr0;                                              /* Stdby and Wake-up Ctrl Reg 0 handle    */
    pmswcr0.U = MODULE_PMS.PMSWCR0.U;                                /* Assign current register value to it    */
    pmswcr0.B.PINAWKEN      = DISABLE_WAKEUP_ON_PINA;                /* DISABLE_WAKEUP_ON_PINA                 */
    pmswcr0.B.PORSTWKEN     = WAKEUP_PORST_ENABLE;                   /*DISABLE/ENABLE_WAKEUP_ON_PORST           */
    pmswcr0.B.PINAEDCON     = TRIGGER_ON_ANY_EDGE;                   /* TRIGGER_ON_ANY_EDGE    */
    pmswcr0.B.ESR0EDCON     = DISABLE_WAKEUP_ON_ESR0;                /* Disable WakeUpTrigger at any ESR0 edge     */
    pmswcr0.B.PWRWKEN       = WAKEUP_ON_VEXT_RAMPUP_DISABLE ;        /* DISABLE WakeUpTrigger on VEXT ramp up      */
    pmswcr0.B.SCRWKEN       = WAKEUP_SCR_ENABLE;                     /* Enable WakeUp on SCR                       */
    pmswcr0.B.STBYRAMSEL    = STANDBY_RAM_IS_SUPPLIED;               /* Standby RAM (CPU0 dLMU RAM) is supplied.   */
    pmswcr0.B.BLNKFIL       = BLANKING_FILTER_DELAY_FOR_WAKE_UP;    /*  */
    MODULE_PMS.PMSWCR0.U = pmswcr0.U;                               /* Assign object to register                  */

    MODULE_PMS.PMSWCR4.B.SCRCLKSEL = 0;                                    //100MHz oscillator can be enabled or disabled based on request from Standby Controller. By default 100 MHz Oscillator is requested by SCR in Standby Mode. more info on page 961

    SCU_PMCSR0.B.REQSLP = REQUEST_STANDBY;

    IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());      /* Set Safety EndInit protection          */
    IfxScuWdt_setCpuEndinit(IfxScuWdt_getCpuWatchdogPassword());            /* Set CPU EndInit - Standby becomes active */
}

/* This function initializes the port pin which drives the LED 1 */
void initLED_1(void)
{
    /* Initialization of the LED used in this example */
    IfxPort_setPinModeOutput(LED_1 , IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    /* Switch OFF the LED */
    IfxPort_setPinHigh(LED_1);
}

/* This function toggles the port pin and wait 500 milliseconds */
void blinkLED_1(void)
{
    IfxPort_togglePin(LED_1);                                                     /* Toggle the state of the LED      */
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));    /* Wait 500 milliseconds                */
}

/* This function initializes the port pin as input pull down*/
void init_input_Pin(void)
{
    IfxPort_setPinModeInput(Push_Button, IfxPort_InputMode_pullDown);
}
int get_Push_Button_status(void)
{
    pin_status=  IfxPort_getPinState(Push_Button);

    return pin_status;

}
/* This function initializes the port pin which drives the LED 2 */
void initLED_2(void)
{
    /* Initialization of the LED used in this example */
    IfxPort_setPinModeOutput(LED_2 , IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    /* Switch OFF the LED */
    IfxPort_setPinHigh(LED_2);
}
void setLED2High(void){

    IfxPort_setPinLow(LED_2);
}
void setLED2Low(void){

    IfxPort_setPinHigh(LED_2);

}
