/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "registers.h"


volatile unsigned int var_1;

void delay(void);
void gpoi_init(void);
void scr_rtcInit(void);

void main()
{


    /* SCU module configurations*/
    SCR_SCU_PAGE = 1;       //Switch to page 1
    SCR_SCU_PMCON1 = 0x59;  //OCDS, T2CCU0, RTC and WCAN enabled

    SCR_SCU_PAGE = 0;       //Switch to page 0
    SCR_SCRINTEXCHG = 0xA0;
    SCR_SCU_PAGE = 1;       //Switch to page 0
    // Enable global interrupt RMAP: X, PAGE: X
    SCR_IEN0 |= (1 << 7) ; // enable global interrupt Set bit 7
    SCR_IEN1 |= (1 << 7) ; // enable node 13 interrupt

    gpoi_init();
    scr_rtcInit();



	while(1){



	}

}
/*****************************************************************************************
 *
 *****************************************************************************************/
void delay(void){

    int i = 0;
    int j = 0;
    for( i = 0; i < 1000; i++){
        for(j = 0; j< 1000; j++){

        }
    }

}
/***********************************************************************************************
 *
 **************************************************************************************************/
void gpoi_init(void){

    /* IO module configurations*/
    SCR_IO_PAGE = 2;        //Switch to page 2
    SCR_P00_PDISC = 0x00;
    SCR_P01_PDISC = 0x00;

    SCR_IO_PAGE = 1;        //Switch to page 1
    SCR_P00_IOCR0 = 0x80;
    SCR_P00_IOCR1 = 0x80;
    SCR_P00_IOCR2 = 0x80;
    SCR_P00_IOCR3 = 0x80;
    SCR_P00_IOCR4 = 0x80;
    SCR_P00_IOCR5 = 0x80;
    SCR_P00_IOCR6 = 0x80;

}
/************************************************************************************************
 *
 *************************************************************************************************/
void scr_rtcInit(void){


/* RTC module configurations*/
    //1s@100Mhz/DIV, we use high speed because 70khz has 30% variation
    SCR_RTC_CR0 = 0xFF;
    SCR_RTC_CR1 = 0xFF;
    SCR_RTC_CR2 = 0xFF;
    SCR_RTC_CR3 = 0x01;
//   RMAP: 0, PAGE: X
    SCR_RTC_CON =  0x17;        // RTC Interrupt Enable, RTC start operation, RTC 100MHz/DIV -> 20MHz 9-bit prescaler is bypassed

}
/*************************************************************************/
/* RTC ISR to blink a LED */
void rtc_interrupt(void) __interrupt (13){
    var_1++;
    SCR_IO_PAGE = 0;
    if(var_1 == 1){
        SCR_P00_OUT |= (1 << 1) ; // Set bit 6
    }
    else if (var_1 == 2){
        SCR_P00_OUT &= ~(1 << 1) ; // Clear bit 5
    }
    else {
        var_1 = 0;
    }

    SCR_RTC_CON &= ~(1 << 6) ;// clear rtc Interrupt flag

}
/***********************************************************************************************************
 *
************************************************************************************************************ */


