/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "registers.h"
#include "scr_header_files.h"


volatile unsigned int FellingEdge = 0;
volatile unsigned int RissingEdge = 0;
volatile unsigned int CaptureFlag = 0;
volatile unsigned int retunr_value;



void delay(void);



void main()
{


    /* SCU module configurations*/
    SCR_SCU_PAGE = 1;       //Switch to page 1
    SCR_SCU_PMCON1 = 0x59;  //OCDS, T2CCU0, RTC and WCAN enabled

    SCR_SCU_PAGE = 0;       //Switch to page 0
    SCR_SCRINTEXCHG = 0xA0;
    SCR_SCU_PAGE = 1;       //Switch to page 0
    // Enable global interrupt RMAP: X, PAGE: X
    SCR_IEN0 |= (1 << 7) ; // enable global interrupt Set bit 7
    SCR_IEN1 |= (1 << 7) ; // enable node 13 interrupt



    gpio_init();




	while(1){

	    SCR_P00_OUT |= (1 << 5) ; // Set bit 5
	    delay();
	     SCR_P00_OUT &= ~(1 << 5) ; // Clear bit 5
	      delay();
	      retunr_value = IsStandbyMode();
	      if(retunr_value == 1){
	          SCR_P00_OUT |= (1 << 4) ;
	      }

	     }



}
/*****************************************************************************************
 *
 *****************************************************************************************/
void delay(void){

    int i = 0;
    int j = 0;
    for( i = 0; i < 1000; i++){
        for(j = 0; j< 1000; j++){

        }
    }

}
/***********************************************************************************************
 *
 **************************************************************************************************/

/************************************************************************************************
 *
 *************************************************************************************************/

/*************************************************************************/
/* RTC ISR to blink a LED */
void rtc_interrupt(void) __interrupt (13){


    SCR_RTC_CON &= ~(1 << 6) ;// clear rtc Interrupt flag

}
/***********************************************************************************************************
 *
************************************************************************************************************ */

/*  ISR Node 8*/
void EXINT2IS_interrupt(void) __interrupt (8){
   /*
    if(FellingEdge == 1){
        SCR_IO_PAGE = 0;
        SCR_P00_OUT |= (1 << 4) ; // Set bit 5
        SCR_P00_OUT &= ~(1 << 3) ; // Clear bit 5
        SCR_P00_OUT &= ~(1 << 5) ; // Clear bit 5
        FellingEdge = 0;
    }
            */

    SCR_SCU_PAGE = 0;
    SCR_IRCON2 &= ~(1 << 0) ; // Clear Bit 2
    SCR_SCU_PAGE = 1;

}
/***********************************************************************************************************
 *
************************************************************************************************************ */
/* ISR Node 9*/
void EXINT5IS_interrupt(void) __interrupt (9){
   /*
    RissingEdge++ ;
    if(RissingEdge == 1){
        FellingEdge++;
        SCR_IO_PAGE = 0;
        SCR_P00_OUT |= (1 << 3) ; // Set bit 5
        SCR_P00_OUT &= ~(1 << 4) ; // Clear bit 5
        SCR_P00_OUT &= ~(1 << 5) ; // Clear bit 5
    }
    if(RissingEdge == 2){

        SCR_IO_PAGE = 0;
        SCR_P00_OUT |= (1 << 5) ; // Set bit 5
        SCR_P00_OUT &= ~(1 << 3) ; // Clear bit 5
        SCR_P00_OUT &= ~(1 << 4) ; // Clear bit 5
        RissingEdge = 0;

    }
                        */
    SCR_SCU_PAGE = 0;
    SCR_IRCON2 &= ~(1 << 1) ; // Clear Bit 2
    SCR_SCU_PAGE = 1;

}
/***********************************************************************************************************
 *
************************************************************************************************************ */

