/**********************************************************************************************************************
 * \file registers.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#ifndef SCR_REG_SDCC_H
#define SCR_REG_SDCC_H 1

/* NVM */
#define ADDR_NVM_STATUS1                0xe1    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_STATUS2                0xe2    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_ADDRP                  0xe3    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_ADDRS                  0xe4    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_CTRL                   0xe5    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_MODE                   0xe6    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_MAP1                   0xe7    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_MAP2                   0xe9    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_BRNG                   0xea    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_PROT                   0xeb    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_SFRSEL                 0xec    /* RMAP=0, PAGE= x - NVM register */
#define ADDR_NVM_SFRDAT                 0xed    /* RMAP=0, PAGE= x - NVM register */

/* SCR 		__sfr __at () 			*/
__sfr __at (0x11) SCR_DAPISC ;                    /* RMAP=x, PAGE= x - DAP Initialization, Status and Control Register */
__sfr __at (0x90) SCR_P00_OUT ;                   /* RMAP=0, PAGE= 0 - Port P00 Output Register */
__sfr __at (0x91) SCR_P00_IN ;                    /* RMAP=0, PAGE= 0 - Port P00 Input Register */
__sfr __at (0x92) SCR_P00_OMSR;                   /* RMAP=0, PAGE= 0 - Port P00 Output Modification Set Register */
__sfr __at (0x93) SCR_P00_OMCR;                   /* RMAP=0, PAGE= 0 - Port P00 Output Modification Clear Register */
__sfr __at (0x94) SCR_P00_OMTR;                   /* RMAP=0, PAGE= 0 - Port P00 Output Modification Toggle Register */
__sfr __at (0x98) SCR_P01_OUT ;                   /* RMAP=0, PAGE= 0 - Port P01 Output Register */
__sfr __at (0x99) SCR_P01_IN;                     /* RMAP=0, PAGE= 0 - Port P01 Input Register */
__sfr __at ( 0x9a) SCR_P01_OMSR  ;                /* RMAP=0, PAGE= 0 - Port P01 Output Modification Set Register */
__sfr __at (0x9b) SCR_P01_OMCR ;                  /* RMAP=0, PAGE= 0 - Port P01 Output Modification Clear Register */
__sfr __at (0x9c) SCR_P01_OMTR ;                  /* RMAP=0, PAGE= 0 - Port P01 Output Modification Toggle Register */
__sfr __at (0xb0) SCR_WCAN_CFG ;                  /* RMAP=0, PAGE= 0 - Wake-Up CAN Configuration Register */
__sfr __at (0xb1) SCR_WCAN_INTMRSLT;              /* RMAP=0, PAGE= 0 - Wake-Up CAN Interrupt Mask Register */
__sfr __at (0xb2) SCR_WCAN_CDR_CTRL ;             /* RMAP=0, PAGE= 0 - CDR Control Register */
__sfr __at (0xb3) SCR_WCAN_CDR_UPPER_CTRL;        /* RMAP=0, PAGE= 0 - CDR Upper Limit Control Register */
__sfr __at (0xb4) SCR_WCAN_CDR_LOWER_CTRL;        /* RMAP=0, PAGE= 0 - CDR Lower Limit Control Register */
__sfr __at ( 0xb5) SCR_WCAN_CDR_MEAS_HIGH ;       /* RMAP=0, PAGE= 0 - CDR Measured High Register */
__sfr __at (0xb6) SCR_WCAN_CDR_MEAS_LOW ;         /* RMAP=0, PAGE= 0 - CDR Measured Low Register */
__sfr __at (0xb7) SCR_WCAN_FD_CTRL  ;             /* RMAP=0, PAGE= 0 - CAN FD Control Register */
__sfr __at (0xc0) SCR_T2_CON  ;                   /* RMAP=0, PAGE= 0 - Timer 2 Control Register */
__sfr __at (0xc1) SCR_T2_MOD ;                    /* RMAP=0, PAGE= 0 - Timer 2 Mode Register */
__sfr __at (0xc2) SCR_T2_RC2L  ;                  /* RMAP=0, PAGE= 0 - Timer 2 Reload/Capture Register, Low Byte */
__sfr __at (0xc3) SCR_T2_RC2H  ;                  /* RMAP=0, PAGE= 0 - Timer 2 Reload/Capture Register, High Byte */
__sfr __at (0xc4) SCR_T2_T2L  ;                   /* RMAP=0, PAGE= 0 - Timer 2, Low Byte */
__sfr __at (0xc5) SCR_T2_T2H ;                    /* RMAP=0, PAGE= 0 - Timer 2, High Byte */
__sfr __at (0xc6) SCR_T2_CON1;                    /* RMAP=0, PAGE= 0 - Timer 2 Control Register 1 */
__sfr __at (0xf2) SCR_IRCON0;                     /* RMAP=0, PAGE= 0 - Interrupt Request Register 0 */
__sfr __at (0xf3) SCR_IRCON1;                     /* RMAP=0, PAGE= 0 - Interrupt Request Register 1 */
__sfr __at (0xf4) SCR_IRCON2;                     /* RMAP=0, PAGE= 0 - Interrupt Request Register 2 */
__sfr __at (0xf5) SCR_SCRINTEXCHG ;               /* RMAP=0, PAGE= 0 - SCR Interrupt Data Exchange Register */
__sfr __at (0xf6) SCR_TCINTEXCHG;                 /* RMAP=0, PAGE= 0 - TriCore Interrupt Data Exchange Register */
__sfr __at (0xf7) SCR_SCU_RSTST;                  /* RMAP=0, PAGE= 0 - SCR Reset Status Register */
__sfr __at (0xf8) SCR_SCU_MRSTST;                 /* RMAP=0, PAGE= 0 - Main Reset Status Register */
__sfr __at ( 0xf9) SCR_SCU_SR ;                   /* RMAP=0, PAGE= 0 - SCU Status Register */
__sfr __at ( 0xfa) SCR_ADCOMP_RES;                /* RMAP=0, PAGE= 0 - ADCOMP Result Register */
__sfr __at ( 0xfb) SCR_ADCOMP_CON ;               /* RMAP=0, PAGE= 0 - ADCOMP Control Register */
__sfr __at (0x81) SCR_WDT_CON ;                   /* RMAP=0, PAGE= X - Watchdog Timer Control Register */
__sfr __at (0x82) SCR_WDT_REL;                    /* RMAP=0, PAGE= X - Watchdog Timer Reload Register */
__sfr __at (0x83) SCR_WDT_WINB;                   /* RMAP=0, PAGE= X - Watchdog Window-Boundary Register */
__sfr __at (0x84) SCR_WDT_L ;                     /* RMAP=0, PAGE= X - Watchdog Timer Low Byte */
__sfr __at (0x85) SCR_WDT_H  ;                    /* RMAP=0, PAGE= X - Watchdog Timer High Byte */
__sfr __at ( 0x89) SCR_SSC_CONOL;                 /* RMAP=0, PAGE= X - Control Register Low [Operation Mode] */
__sfr __at (0x89) SCR_SSC_CONPL;                  /* RMAP=0, PAGE= X - Control Register Low [Programming Mode] */
__sfr __at (0x8a) SCR_SSC_CONPH;                  /* RMAP=0, PAGE= X - Control Register High [Programming Mode] */
__sfr __at (0x8a) SCR_SSC_CONOH ;                 /* RMAP=0, PAGE= X - Control Register High [Operation Mode] */
__sfr __at ( 0x8b) SCR_SSC_TBL ;                  /* RMAP=0, PAGE= X - Transmitter Buffer Register */
__sfr __at ( 0x8c) SCR_SSC_RBL;                   /* RMAP=0, PAGE= X - Receiver Buffer Register */
__sfr __at (0x8d) SCR_SSC_BRL ;                   /* RMAP=0, PAGE= X - Baud Rate Timer Reload Register Low */
__sfr __at (0x8e) SCR_SSC_BRH ;                   /* RMAP=0, PAGE= X - Baud Rate Timer Reload Register High */
__sfr __at (0x8f) SCR_IO_PAGE ;                   /* RMAP=0, PAGE= X - Page Register for Port SFRs */
__sfr __at (0xb8) SCR_WCAN_PAGE;                  /* RMAP=0, PAGE= X - Page Register for WCAN */
__sfr __at (0xb9) SCR_UART_SCON ;                 /* RMAP=0, PAGE= X - Serial Channel Control Register */
__sfr __at (0xba) SCR_UART_SBUF ;                 /* RMAP=0, PAGE= X - Serial Data Buffer */
__sfr __at (0xbc) SCR_UART_BGL ;                  /* RMAP=0, PAGE= X - Baudrate Timer/Reload Register, Low Byte */
__sfr __at (0xbd) SCR_UART_BCON ;                 /* RMAP=0, PAGE= X - Baudrate Control Register */
__sfr __at (0xbe) SCR_UART_LINST;                 /* RMAP=0, PAGE= X - LIN Status Register */
__sfr __at (0xbf) SCR_UART_BGH ;                  /* RMAP=0, PAGE= X - Baudrate Timer/Reload Register, High Byte */
__sfr __at (0xc7) SCR_T2CCU_PAGE ;                /* RMAP=0, PAGE= X - Page Register for T2CCU */
__sfr __at (0xe1) SCR_RTC_CON;                    /* RMAP=0, PAGE= X - Real-Time Clock Control Register */
__sfr __at (0xe2) SCR_RTC_CNT0;                   /* RMAP=0, PAGE= X - Count Clock Register 0 */
__sfr __at (0xe3) SCR_RTC_CNT1 ;                  /* RMAP=0, PAGE= X - Count Clock Register 1 */
__sfr __at (0xe4) SCR_RTC_CNT2 ;                  /* RMAP=0, PAGE= X - Count Clock Register 2 */
__sfr __at (0xe5) SCR_RTC_CNT3 ;                  /* RMAP=0, PAGE= X - Count Clock Register 3 */
__sfr __at (0xe6) SCR_RTC_CR0 ;                   /* RMAP=0, PAGE= X - Real-Time Clock Compare/Capture Register 0 */
__sfr __at (0xe7) SCR_RTC_CR1;                    /* RMAP=0, PAGE= X - Real-Time Clock Compare/Capture Register 1 */
__sfr __at (0xe8) SCR_RTC_CR2 ;                  /* RMAP=0, PAGE= X - Real-Time Clock Compare/Capture Register 2 */
__sfr __at (0xe9) SCR_RTC_CR3 ;                   /* RMAP=0, PAGE= X - Real-Time Clock Compare/Capture Register 3 */
__sfr __at (0xf1) SCR_SCU_PAGE ;                  /* RMAP=0, PAGE= X - Page Register for SFRs */
__sfr __at (0xf1) SCR_DBG_MMCR ;                  /* RMAP=1, PAGE= X - Monitor Mode Control Register */
__sfr __at (0xf2) SCR_DBG_MMCR2;                 /* RMAP=1, PAGE= X - Monitor Mode Control Register 2 */
__sfr __at (0xf3) SCR_DBG_MMSR ;                  /* RMAP=1, PAGE= X - Monitor Mode Status Register */
__sfr __at (0xf4) SCR_DBG_MMBPCR;                 /* RMAP=1, PAGE= X - BreakPoints Control Register */
__sfr __at (0xf5) SCR_DBG_MMICR ;                 /* RMAP=1, PAGE= X - Monitor Mode Interrupt Control Register */
__sfr __at (0xf6) SCR_DBG_MMDR ;                  /* RMAP=1, PAGE= X - Monitor Mode Data Register - Receive */
__sfr __at (0xf7) SCR_DBG_HWBPSR;                /* RMAP=1, PAGE= X - Hardware Breakpoints Select Register */
__sfr __at (0xf8) SCR_DBG_HWBPDR;                 /* RMAP=1, PAGE= X - Hardware Breakpoints Data Register */
__sfr __at (0xf9) SCR_DBG_MMWR1 ;                 /* RMAP=1, PAGE= X - Monitor Work Register 1 */
__sfr __at (0xfa) SCR_DBG_MMWR2;                  /* RMAP=1, PAGE= X - Monitor Work Register 2 */
__sfr __at (0x86) SCR_PASSWD ;                    /* RMAP=X, PAGE= X - Password Register */
__sfr __at (0x87) SCR_XADDRH;                     /* RMAP=X, PAGE= X - On-Chip XRAM Address Higher Order */
__sfr __at (0x88) SCR_SYSCON0 ;                   /* RMAP=X, PAGE= X - System Control Register 0 */
__sfr __at (0xc9) SCR_T01_TCON ;                  /* RMAP=X, PAGE= X - Timer 0/1 Control Register */
__sfr __at (0xca) SCR_T01_TMOD;                   /* RMAP=X, PAGE= X - Timer Mode Register */
__sfr __at (0xcb) SCR_T01_TL0  ;                  /* RMAP=X, PAGE= X - Timer 0 Low Byte */
__sfr __at (0xcc) SCR_T01_TL1;                    /* RMAP=X, PAGE= X - Timer 1 Low Byte */
__sfr __at (0xcd) SCR_T01_TH0;                    /* RMAP=X, PAGE= X - Timer 0 High Byte */
__sfr __at (0xce) SCR_T01_TH1 ;                   /* RMAP=X, PAGE= X - Timer 1 High Byte */
__sfr __at (0xd0) SCR_PSW  ;                      /* RMAP=X, PAGE= X - Program Status Word Register */
__sfr __at (0xd1) SCR_IEN1;                       /* RMAP=X, PAGE= X - Interrupt Enable Register 1 */
__sfr __at (0xd2) SCR_IPH ;                       /* RMAP=X, PAGE= X - Interrupt Priority High Register */
__sfr __at (0xd3) SCR_IPH1 ;                      /* RMAP=X, PAGE= X - Interrupt Priority 1 High Register */
__sfr __at (0xd4) SCR_SP   ;                      /* RMAP=X, PAGE= X - Stack Pointer */
__sfr __at (0xd5) SCR_DPL;                        /* RMAP=X, PAGE= X - Data Pointer Low Byte */
__sfr __at (0xd6) SCR_DPH;                        /* RMAP=X, PAGE= X - Data Pointer High Byte */
__sfr __at (0xd7) SCR_EO ;                        /* RMAP=X, PAGE= X - Extended Operation Register */
__sfr __at (0xd8) SCR_IEN0;                       /* RMAP=X, PAGE= X - Interrupt Enable Register 0 */
__sfr __at (0xd9) SCR_PCON;                       /* RMAP=X, PAGE= X - Power Control Register */
__sfr __at (0xda) SCR_B;                          /* RMAP=X, PAGE= X - B Register */
__sfr __at (0xdb) SCR_IP1 ;                       /* RMAP=X, PAGE= X - Interrupt Priority 1 Register */
__sfr __at (0xdc) SCR_IP;                         /* RMAP=X, PAGE= X - Interrupt Priority Register */
__sfr __at (0xe0) SCR_ACC ;                       /* RMAP=X, PAGE= X - Accumulator */
__sfr __at (0x90) SCR_P00_IOCR0 ;                 /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 0 */
__sfr __at (0x91) SCR_P00_IOCR1 ;                 /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 1 */


//  sfr  __at (0x90) SCR_P00_IOCR0; /* special function register P0 at location0x80 */

// __sfr __at (0xF0) P0_OD  ;

// __sfr __at () 

__sfr __at (0x90) SCR_P00_IOCR0   ;               /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 0 */
__sfr __at (0x91) SCR_P00_IOCR1  ;               /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 1 */
__sfr __at (0x92) SCR_P00_IOCR2 ;                 /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 2 */
__sfr __at (0x93) SCR_P00_IOCR3  ;                /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 3 */
__sfr __at (0x94) SCR_P00_IOCR4  ;                /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 4 */
__sfr __at (0x95) SCR_P00_IOCR5  ;                /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 5 */
__sfr __at (0x96) SCR_P00_IOCR6  ;                /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 6 */
__sfr __at (0x97) SCR_P00_IOCR7 ;                /* RMAP=0, PAGE= 1 - Port P00 Input/Output Control Register 7 */


__sfr __at (0x98) SCR_P01_IOCR0  ;                /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 0 */
__sfr __at (0x99) SCR_P01_IOCR1 ;                /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 1 */
__sfr __at (0x9a) SCR_P01_IOCR2  ;                /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 2 */
__sfr __at (0x9b) SCR_P01_IOCR3   ;               /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 3 */
__sfr __at (0x9c) SCR_P01_IOCR4   ;               /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 4 */
__sfr __at (0x9d) SCR_P01_IOCR5 ;                /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 5 */
__sfr __at (0x9e) SCR_P01_IOCR6  ;                /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 6 */
__sfr __at (0x9f) SCR_P01_IOCR7  ;                /* RMAP=0, PAGE= 1 - Port P01 Input/Output Control Register 7 */


__sfr __at (0xb0) SCR_WCAN_INTESTAT0 ;            /* RMAP=0, PAGE= 1 - Wake-Up CAN Interrupt and Event Status Register 0 */
__sfr __at (0xb1) SCR_WCAN_INTESTAT1;            /* RMAP=0, PAGE= 1 - Wake-Up CAN Interrupt and Event Status Register 1 */
__sfr __at (0xb2) SCR_WCAN_FRMERRCNT ;            /* RMAP=0, PAGE= 1 - Wake-Up CAN Error Counter Register */
__sfr __at (0xb3) SCR_WCAN_INTESCLR0  ;          /* RMAP=0, PAGE= 1 - Wake-Up CAN Interrupt and Event Status Clear Register 0 */
__sfr __at (0xb4) SCR_WCAN_INTESCLR1;             /* RMAP=0, PAGE= 1 - Wake-Up CAN Interrupt and Event Status Clear Register 1 */
__sfr __at (0xb5) SCR_WCAN_BTL1_CTRL ;            /* RMAP=0, PAGE= 1 - Bit Timing Logic 1 Control Register */
__sfr __at (0xb6) SCR_WCAN_BTL2_CTRL ;            /* RMAP=0, PAGE= 1 - Bit Timing Logic 2 Control Register */
__sfr __at (0xb7) SCR_WCAN_DLC_CTRL;              /* RMAP=0, PAGE= 1 - Message Data Length Code Control Register */
__sfr __at (0xc0) SCR_T2CCU_CCEN  ;               /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Enable Register */
__sfr __at (0xc1) SCR_T2CCU_CCTBSEL ;             /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Time Base Select Register */
__sfr __at (0xc2) SCR_T2CCU_CCTRELL   ;           /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Timer Reload Register Low */
__sfr __at (0xc3) SCR_T2CCU_CCTRELH ;             /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Timer Reload Register High */
__sfr __at (0xc4) SCR_T2CCU_CCTL ;                /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Timer Register Low */
__sfr __at (0xc5) SCR_T2CCU_CCTH ;                /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Timer Register High */
__sfr __at (0xc6) SCR_T2CCU_CCTCON;               /* RMAP=0, PAGE= 1 - T2CCU Capture/Compare Timer Control Register */
__sfr __at (0xf2) SCR_NMISR;                      /* RMAP=0, PAGE= 1 - NMI Status Register */
__sfr __at (0xf3) SCR_NMICON ;                    /* RMAP=0, PAGE= 1 - NMI Control Register */
__sfr __at (0xf4) SCR_EXICON0;                    /* RMAP=0, PAGE= 1 - External Interrupt Control Register 0 */
__sfr __at ( 0xf5) SCR_EXICON1;                   /* RMAP=0, PAGE= 1 - External Interrupt Control Register 1 */
__sfr __at (0xf6) SCR_EXICON2 ;                   /* RMAP=0, PAGE= 1 - External Interrupt Control Register 2 */
__sfr __at (0xf7) SCR_EXICON3 ;                   /* RMAP=0, PAGE= 1 - External Interrupt Control Register 3 */
__sfr __at (0xf8) SCR_SCU_MODIEN ;                /* RMAP=0, PAGE= 1 - Peripheral Interrupt Enable Register */
__sfr __at (0xf9) SCR_SCU_RSTCON;                 /* RMAP=0, PAGE= 1 - Reset Control Register */
__sfr __at (0xfa) SCR_SCU_CMCON;                  /* RMAP=0, PAGE= 1 - Clock Control Register */
__sfr __at (0xfb) SCR_SCU_PMCON1;                 /* RMAP=0, PAGE= 1 - Peripheral Management Control Register 1 */
__sfr __at (0xfc) SCR_SCU_STDBYWKP;               /* RMAP=0, PAGE= 1 - Standby Mode Wake-Up Register */
__sfr __at (0xfd ) SCR_EVRADCSTAT0 ;              /* RMAP=0, PAGE= 1 - EVR ADC Status Register 0 */
__sfr __at (0xfe) SCR_EVRADCSTAT1 ;               /* RMAP=0, PAGE= 1 - EVR ADC Status Register 1 */
__sfr __at (0xff) SCR_EVRADCSTAT2;                /* RMAP=0, PAGE= 1 - EVR ADC Status Register 2 */
__sfr __at (0x90) SCR_P00_PDR0;                   /* RMAP=0, PAGE= 2 - Port P00 Pad Driver Mode 0 Register */
__sfr __at (0x91 ) SCR_P00_PDR2;                  /* RMAP=0, PAGE= 2 - Port P00 Pad Driver Mode 2 Register */
__sfr __at (0x92) SCR_P00_PDR4;                   /* RMAP=0, PAGE= 2 - Port P00 Pad Driver Mode 4 Register */
__sfr __at (0x93) SCR_P00_PDR6 ;                  /* RMAP=0, PAGE= 2 - Port P00 Pad Driver Mode 6 Register */
__sfr __at (0x95) SCR_P00_PDISC ;                 /* RMAP=0, PAGE= 2 - Port P00 Pin Function Decision Control Register */
__sfr __at (0x98 ) SCR_P01_PDR0 ;                 /* RMAP=0, PAGE= 2 - Port P01 Pad Driver Mode 0 Register */
__sfr __at (0x99) SCR_P01_PDR2 ;                  /* RMAP=0, PAGE= 2 - Port P01 Pad Driver Mode 2 Register */
__sfr __at (0x9a) CR_P01_PDR4;                   /* RMAP=0, PAGE= 2 - Port P01 Pad Driver Mode 4 Register */
__sfr __at (0x9b) SCR_P01_PDR6;                   /* RMAP=0, PAGE= 2 - Port P01 Pad Driver Mode 6 Register */
__sfr __at (0x9d ) SCR_P01_PDISC;                 /* RMAP=0, PAGE= 2 - Port P01 Pin Function Decision Control Register */
#define ADDR_SCR_WCAN_ID0_CTRL          0xb0    /* RMAP=0, PAGE= 2 - Message Identifier Control Register 0 */
#define ADDR_SCR_WCAN_ID1_CTRL          0xb1    /* RMAP=0, PAGE= 2 - Message Identifier Control Register 1 */
#define ADDR_SCR_WCAN_ID2_CTRL          0xb2    /* RMAP=0, PAGE= 2 - Message Identifier Control Register 2 */
#define ADDR_SCR_WCAN_ID3_CTRL          0xb3    /* RMAP=0, PAGE= 2 - Message Identifier Control Register 3 */
#define ADDR_SCR_WCAN_MASK_ID0_CTRL     0xb4    /* RMAP=0, PAGE= 2 - Message Identifier Mask Register 0 */
#define ADDR_SCR_WCAN_MASK_ID1_CTRL     0xb5    /* RMAP=0, PAGE= 2 - Message Identifier Mask Register 1 */
#define ADDR_SCR_WCAN_MASK_ID2_CTRL     0xb6    /* RMAP=0, PAGE= 2 - Message Identifier Mask Register 2 */
#define ADDR_SCR_WCAN_MASK_ID3_CTRL     0xb7    /* RMAP=0, PAGE= 2 - Message Identifier Mask Register 3 */
__sfr __at (0xc0) SCR_T2CCU_COSHDW ;              /* RMAP=0, PAGE= 2 - T2CCU Compare Shadow Register */
__sfr __at (0xc1) SCR_T2CCU_CC0L ;                /* RMAP=0, PAGE= 2 - T2CCU Capture/Compare Register 0 Low */
__sfr __at (0xc2) SCR_T2CCU_CC1L ;                /* RMAP=0, PAGE= 2 - T2CCU Capture/Compare Register 1 Low */
__sfr __at ( 0xc3) SCR_T2CCU_CC2L;                /* RMAP=0, PAGE= 2 - T2CCU Capture/Compare Register 2 Low */
__sfr __at (0xc4) SCR_T2CCU_CC0H ;                /* RMAP=0, PAGE= 2 - T2CCU Capture/Compare Register 0 High */
__sfr __at (0xc5) SCR_T2CCU_CC1H ;                /* RMAP=0, PAGE= 2 - T2CCU Capture/Compare Register 1 High */
__sfr __at (0xc6) SCR_T2CCU_CC2H ;                /* RMAP=0, PAGE= 2 - T2CCU Capture/Compare Register 2 High */
__sfr __at (0xf2) SCR_MODPISEL0 ;                 /* RMAP=0, PAGE= 2 - Peripheral Input Select Register 0 */
__sfr __at (0xf3) SCR_MODPISEL1;                  /* RMAP=0, PAGE= 2 - Peripheral Input Select Register 1 */
__sfr __at (0xf4) SCR_MODPISEL2 ;                 /* RMAP=0, PAGE= 2 - Peripheral Input Select Register 2 */
__sfr __at (0xf5) SCR_MODPISEL3 ;                 /* RMAP=0, PAGE= 2 - Peripheral Input Select Register 3 */
__sfr __at (0xf6) SCR_MODPISEL4 ;                 /* RMAP=0, PAGE= 2 - Peripheral Input Select Register 4 */
__sfr __at (0xf7) SCR_MODPISEL5 ;                 /* RMAP=0, PAGE= 2 - Peripheral Input Select Register 5 */
__sfr __at (0xf8) SCR_SCR_HWCFG;                  /* RMAP=0, PAGE= 2 - Hardware Configuration Register */
__sfr __at (0xf9) SCR_DBG_MODSUSP;                /* RMAP=0, PAGE= 2 - Module Suspend Control Register */
__sfr __at (0xb0) SCR_WCAN_DATA0_CTRL ;           /* RMAP=0, PAGE= 3 - DATA0 Control Register */
#define ADDR_SCR_WCAN_DATA1_CTRL        0xb1    /* RMAP=0, PAGE= 3 - DATA1 Control Register */
#define ADDR_SCR_WCAN_DATA2_CTRL        0xb2    /* RMAP=0, PAGE= 3 - DATA2 Control Register */
#define ADDR_SCR_WCAN_DATA3_CTRL        0xb3    /* RMAP=0, PAGE= 3 - DATA3 Control Register */
#define ADDR_SCR_WCAN_DATA4_CTRL        0xb4    /* RMAP=0, PAGE= 3 - DATA4 Control Register */
#define ADDR_SCR_WCAN_DATA5_CTRL        0xb5    /* RMAP=0, PAGE= 3 - DATA5 Control Register */
#define ADDR_SCR_WCAN_DATA6_CTRL        0xb6    /* RMAP=0, PAGE= 3 - DATA6 Control Register */
#define ADDR_SCR_WCAN_DATA7_CTRL        0xb7    /* RMAP=0, PAGE= 3 - DATA7 Control Register */
__sfr __at (0xc0) SCR_T2CCU_COCON ;               /* RMAP=0, PAGE= 3 - T2CCU Compare Control Register */
__sfr __at (0xc1) SCR_T2CCU_CC3L ;                /* RMAP=0, PAGE= 3 - T2CCU Capture/Compare Register 3 Low */
__sfr __at (0xc2) SCR_T2CCU_CC4L;                 /* RMAP=0, PAGE= 3 - T2CCU Capture/Compare Register 4 Low */
__sfr __at (0xc3) SCR_T2CCU_CC5L ;                /* RMAP=0, PAGE= 3 - T2CCU Capture/Compare Register 5 Low */
__sfr __at (0xc4) SCR_T2CCU_CC3H ;                /* RMAP=0, PAGE= 3 - T2CCU Capture/Compare Register 3 High */
__sfr __at (0xc5) SCR_T2CCU_CC4H  ;               /* RMAP=0, PAGE= 3 - T2CCU Capture/Compare Register 4 High */
__sfr __at (0xc6) SCR_T2CCU_CC5H ;                /* RMAP=0, PAGE= 3 - T2CCU Capture/Compare Register 5 High */
__sfr __at (0xc2) SCR_T2CCU_CCTDTCL ;             /* RMAP=0, PAGE= 4 - T2CCU Capture/Compare Timer Dead-Time Control Register Low */
__sfr __at (0xc3) SCR_T2CCU_CCTDTCH  ;            /* RMAP=0, PAGE= 4 - T2CCU Capture/Compare Timer Dead-Time Control Register High */
__sfr __at (0xfa) SCR_ADCOMP_RES  ;               /* RMAP=0, PAGE= 0 - ADCOMP Result Register */
__sfr __at (0xfb) SCR_ADCOMP_CON;                 /* RMAP=0, PAGE= 0 - ADCOMP Control Register */






#define RMAP_NVM_STATUS1                0
#define RMAP_NVM_STATUS2                0
#define RMAP_NVM_ADDRP                  0
#define RMAP_NVM_ADDRS                  0
#define RMAP_NVM_CTRL                   0
#define RMAP_NVM_MODE                   0
#define RMAP_NVM_MAP1                   0
#define RMAP_NVM_MAP2                   0
#define RMAP_NVM_BRNG                   0
#define RMAP_NVM_PROT                   0
#define RMAP_NVM_SFRSEL                 0
#define RMAP_NVM_SFRDAT                 0
#define RMAP_SCR_P00_OUT                0
#define PAGE_SCR_P00_OUT                0
#define RMAP_SCR_P00_IN                 0
#define PAGE_SCR_P00_IN                 0
#define RMAP_SCR_P00_OMSR               0
#define PAGE_SCR_P00_OMSR               0
#define RMAP_SCR_P00_OMCR               0
#define PAGE_SCR_P00_OMCR               0
#define RMAP_SCR_P00_OMTR               0
#define PAGE_SCR_P00_OMTR               0
#define RMAP_SCR_P01_OUT                0
#define PAGE_SCR_P01_OUT                0
#define RMAP_SCR_P01_IN                 0
#define PAGE_SCR_P01_IN                 0
#define RMAP_SCR_P01_OMSR               0
#define PAGE_SCR_P01_OMSR               0
#define RMAP_SCR_P01_OMCR               0
#define PAGE_SCR_P01_OMCR               0
#define RMAP_SCR_P01_OMTR               0
#define PAGE_SCR_P01_OMTR               0
#define RMAP_SCR_WCAN_CFG               0
#define PAGE_SCR_WCAN_CFG               0
#define RMAP_SCR_WCAN_INTMRSLT          0
#define PAGE_SCR_WCAN_INTMRSLT          0
#define RMAP_SCR_WCAN_CDR_CTRL          0
#define PAGE_SCR_WCAN_CDR_CTRL          0
#define RMAP_SCR_WCAN_CDR_UPPER_CTRL    0
#define PAGE_SCR_WCAN_CDR_UPPER_CTRL    0
#define RMAP_SCR_WCAN_CDR_LOWER_CTRL    0
#define PAGE_SCR_WCAN_CDR_LOWER_CTRL    0
#define RMAP_SCR_WCAN_CDR_MEAS_HIGH     0
#define PAGE_SCR_WCAN_CDR_MEAS_HIGH     0
#define RMAP_SCR_WCAN_CDR_MEAS_LOW      0
#define PAGE_SCR_WCAN_CDR_MEAS_LOW      0
#define RMAP_SCR_WCAN_FD_CTRL           0
#define PAGE_SCR_WCAN_FD_CTRL           0
#define RMAP_SCR_T2_CON                 0
#define PAGE_SCR_T2_CON                 0
#define RMAP_SCR_T2_MOD                 0
#define PAGE_SCR_T2_MOD                 0
#define RMAP_SCR_T2_RC2L                0
#define PAGE_SCR_T2_RC2L                0
#define RMAP_SCR_T2_RC2H                0
#define PAGE_SCR_T2_RC2H                0
#define RMAP_SCR_T2_T2L                 0
#define PAGE_SCR_T2_T2L                 0
#define RMAP_SCR_T2_T2H                 0
#define PAGE_SCR_T2_T2H                 0
#define RMAP_SCR_T2_CON1                0
#define PAGE_SCR_T2_CON1                0
#define RMAP_SCR_IRCON0                 0
#define PAGE_SCR_IRCON0                 0
#define RMAP_SCR_IRCON1                 0
#define PAGE_SCR_IRCON1                 0
#define RMAP_SCR_IRCON2                 0
#define PAGE_SCR_IRCON2                 0
#define RMAP_SCR_SCRINTEXCHG            0
#define PAGE_SCR_SCRINTEXCHG            0
#define RMAP_SCR_TCINTEXCHG             0
#define PAGE_SCR_TCINTEXCHG             0
#define RMAP_SCR_SCU_RSTST              0
#define PAGE_SCR_SCU_RSTST              0
#define RMAP_SCR_SCU_MRSTST             0
#define PAGE_SCR_SCU_MRSTST             0
#define RMAP_SCR_SCU_SR                 0
#define PAGE_SCR_SCU_SR                 0
#define RMAP_SCR_ADCOMP_RES             0
#define PAGE_SCR_ADCOMP_RES             0
#define RMAP_SCR_ADCOMP_CON             0
#define PAGE_SCR_ADCOMP_CON             0
#define RMAP_SCR_WDT_CON                0
#define RMAP_SCR_WDT_REL                0
#define RMAP_SCR_WDT_WINB               0
#define RMAP_SCR_WDT_L                  0
#define RMAP_SCR_WDT_H                  0
#define RMAP_SCR_SSC_CONOL              0
#define RMAP_SCR_SSC_CONPL              0
#define RMAP_SCR_SSC_CONPH              0
#define RMAP_SCR_SSC_CONOH              0
#define RMAP_SCR_SSC_TBL                0
#define RMAP_SCR_SSC_RBL                0
#define RMAP_SCR_SSC_BRL                0
#define RMAP_SCR_SSC_BRH                0
#define RMAP_SCR_IO_PAGE                0
#define RMAP_SCR_WCAN_PAGE              0
#define RMAP_SCR_UART_SCON              0
#define RMAP_SCR_UART_SBUF              0
#define RMAP_SCR_UART_BGL               0
#define RMAP_SCR_UART_BCON              0
#define RMAP_SCR_UART_LINST             0
#define RMAP_SCR_UART_BGH               0
#define RMAP_SCR_T2CCU_PAGE             0
#define RMAP_SCR_RTC_CON                0
#define RMAP_SCR_RTC_CNT0               0
#define RMAP_SCR_RTC_CNT1               0
#define RMAP_SCR_RTC_CNT2               0
#define RMAP_SCR_RTC_CNT3               0
#define RMAP_SCR_RTC_CR0                0
#define RMAP_SCR_RTC_CR1                0
#define RMAP_SCR_RTC_CR2                0
#define RMAP_SCR_RTC_CR3                0
#define RMAP_SCR_SCU_PAGE               0
#define RMAP_SCR_DBG_MMCR               1
#define RMAP_SCR_DBG_MMCR2              1
#define RMAP_SCR_DBG_MMSR               1
#define RMAP_SCR_DBG_MMBPCR             1
#define RMAP_SCR_DBG_MMICR              1
#define RMAP_SCR_DBG_MMDR               1
#define RMAP_SCR_DBG_HWBPSR             1
#define RMAP_SCR_DBG_HWBPDR             1
#define RMAP_SCR_DBG_MMWR1              1
#define RMAP_SCR_DBG_MMWR2              1
#define RMAP_SCR_P00_IOCR0              0
#define PAGE_SCR_P00_IOCR0              1
#define RMAP_SCR_P00_IOCR1              0
#define PAGE_SCR_P00_IOCR1              1
#define RMAP_SCR_P00_IOCR2              0
#define PAGE_SCR_P00_IOCR2              1
#define RMAP_SCR_P00_IOCR3              0
#define PAGE_SCR_P00_IOCR3              1
#define RMAP_SCR_P00_IOCR4              0
#define PAGE_SCR_P00_IOCR4              1
#define RMAP_SCR_P00_IOCR5              0
#define PAGE_SCR_P00_IOCR5              1
#define RMAP_SCR_P00_IOCR6              0
#define PAGE_SCR_P00_IOCR6              1
#define RMAP_SCR_P00_IOCR7              0
#define PAGE_SCR_P00_IOCR7              1
#define RMAP_SCR_P01_IOCR0              0
#define PAGE_SCR_P01_IOCR0              1
#define RMAP_SCR_P01_IOCR1              0
#define PAGE_SCR_P01_IOCR1              1
#define RMAP_SCR_P01_IOCR2              0
#define PAGE_SCR_P01_IOCR2              1
#define RMAP_SCR_P01_IOCR3              0
#define PAGE_SCR_P01_IOCR3              1
#define RMAP_SCR_P01_IOCR4              0
#define PAGE_SCR_P01_IOCR4              1
#define RMAP_SCR_P01_IOCR5              0
#define PAGE_SCR_P01_IOCR5              1
#define RMAP_SCR_P01_IOCR6              0
#define PAGE_SCR_P01_IOCR6              1
#define RMAP_SCR_P01_IOCR7              0
#define PAGE_SCR_P01_IOCR7              1
#define RMAP_SCR_WCAN_INTESTAT0         0
#define PAGE_SCR_WCAN_INTESTAT0         1
#define RMAP_SCR_WCAN_INTESTAT1         0
#define PAGE_SCR_WCAN_INTESTAT1         1
#define RMAP_SCR_WCAN_FRMERRCNT         0
#define PAGE_SCR_WCAN_FRMERRCNT         1
#define RMAP_SCR_WCAN_INTESCLR0         0
#define PAGE_SCR_WCAN_INTESCLR0         1
#define RMAP_SCR_WCAN_INTESCLR1         0
#define PAGE_SCR_WCAN_INTESCLR1         1
#define RMAP_SCR_WCAN_BTL1_CTRL         0
#define PAGE_SCR_WCAN_BTL1_CTRL         1
#define RMAP_SCR_WCAN_BTL2_CTRL         0
#define PAGE_SCR_WCAN_BTL2_CTRL         1
#define RMAP_SCR_WCAN_DLC_CTRL          0
#define PAGE_SCR_WCAN_DLC_CTRL          1
#define RMAP_SCR_T2CCU_CCEN             0
#define PAGE_SCR_T2CCU_CCEN             1
#define RMAP_SCR_T2CCU_CCTBSEL          0
#define PAGE_SCR_T2CCU_CCTBSEL          1
#define RMAP_SCR_T2CCU_CCTRELL          0
#define PAGE_SCR_T2CCU_CCTRELL          1
#define RMAP_SCR_T2CCU_CCTRELH          0
#define PAGE_SCR_T2CCU_CCTRELH          1
#define RMAP_SCR_T2CCU_CCTL             0
#define PAGE_SCR_T2CCU_CCTL             1
#define RMAP_SCR_T2CCU_CCTH             0
#define PAGE_SCR_T2CCU_CCTH             1
#define RMAP_SCR_T2CCU_CCTCON           0
#define PAGE_SCR_T2CCU_CCTCON           1
#define RMAP_SCR_NMISR                  0
#define PAGE_SCR_NMISR                  1
#define RMAP_SCR_NMICON                 0
#define PAGE_SCR_NMICON                 1
#define RMAP_SCR_EXICON0                0
#define PAGE_SCR_EXICON0                1
#define RMAP_SCR_EXICON1                0
#define PAGE_SCR_EXICON1                1
#define RMAP_SCR_EXICON2                0
#define PAGE_SCR_EXICON2                1
#define RMAP_SCR_EXICON3                0
#define PAGE_SCR_EXICON3                1
#define RMAP_SCR_SCU_MODIEN             0
#define PAGE_SCR_SCU_MODIEN             1
#define RMAP_SCR_SCU_RSTCON             0
#define PAGE_SCR_SCU_RSTCON             1
#define RMAP_SCR_SCU_CMCON              0
#define PAGE_SCR_SCU_CMCON              1
#define RMAP_SCR_SCU_PMCON1             0
#define PAGE_SCR_SCU_PMCON1             1
#define RMAP_SCR_SCU_STDBYWKP           0
#define PAGE_SCR_SCU_STDBYWKP           1
#define RMAP_SCR_EVRADCSTAT0            0
#define PAGE_SCR_EVRADCSTAT0            1
#define RMAP_SCR_EVRADCSTAT1            0
#define PAGE_SCR_EVRADCSTAT1            1
#define RMAP_SCR_EVRADCSTAT2            0
#define PAGE_SCR_EVRADCSTAT2            1
#define RMAP_SCR_P00_PDR0               0
#define PAGE_SCR_P00_PDR0               2
#define RMAP_SCR_P00_PDR2               0
#define PAGE_SCR_P00_PDR2               2
#define RMAP_SCR_P00_PDR4               0
#define PAGE_SCR_P00_PDR4               2
#define RMAP_SCR_P00_PDR6               0
#define PAGE_SCR_P00_PDR6               2
#define RMAP_SCR_P00_PDISC              0
#define PAGE_SCR_P00_PDISC              2
#define RMAP_SCR_P01_PDR0               0
#define PAGE_SCR_P01_PDR0               2
#define RMAP_SCR_P01_PDR2               0
#define PAGE_SCR_P01_PDR2               2
#define RMAP_SCR_P01_PDR4               0
#define PAGE_SCR_P01_PDR4               2
#define RMAP_SCR_P01_PDR6               0
#define PAGE_SCR_P01_PDR6               2
#define RMAP_SCR_P01_PDISC              0
#define PAGE_SCR_P01_PDISC              2
#define RMAP_SCR_WCAN_ID0_CTRL          0
#define PAGE_SCR_WCAN_ID0_CTRL          2
#define RMAP_SCR_WCAN_ID1_CTRL          0
#define PAGE_SCR_WCAN_ID1_CTRL          2
#define RMAP_SCR_WCAN_ID2_CTRL          0
#define PAGE_SCR_WCAN_ID2_CTRL          2
#define RMAP_SCR_WCAN_ID3_CTRL          0
#define PAGE_SCR_WCAN_ID3_CTRL          2
#define RMAP_SCR_WCAN_MASK_ID0_CTRL     0
#define PAGE_SCR_WCAN_MASK_ID0_CTRL     2
#define RMAP_SCR_WCAN_MASK_ID1_CTRL     0
#define PAGE_SCR_WCAN_MASK_ID1_CTRL     2
#define RMAP_SCR_WCAN_MASK_ID2_CTRL     0
#define PAGE_SCR_WCAN_MASK_ID2_CTRL     2
#define RMAP_SCR_WCAN_MASK_ID3_CTRL     0
#define PAGE_SCR_WCAN_MASK_ID3_CTRL     2
#define RMAP_SCR_T2CCU_COSHDW           0
#define PAGE_SCR_T2CCU_COSHDW           2
#define RMAP_SCR_T2CCU_CC0L             0
#define PAGE_SCR_T2CCU_CC0L             2
#define RMAP_SCR_T2CCU_CC1L             0
#define PAGE_SCR_T2CCU_CC1L             2
#define RMAP_SCR_T2CCU_CC2L             0
#define PAGE_SCR_T2CCU_CC2L             2
#define RMAP_SCR_T2CCU_CC0H             0
#define PAGE_SCR_T2CCU_CC0H             2
#define RMAP_SCR_T2CCU_CC1H             0
#define PAGE_SCR_T2CCU_CC1H             2
#define RMAP_SCR_T2CCU_CC2H             0
#define PAGE_SCR_T2CCU_CC2H             2
#define RMAP_SCR_MODPISEL0              0
#define PAGE_SCR_MODPISEL0              2
#define RMAP_SCR_MODPISEL1              0
#define PAGE_SCR_MODPISEL1              2
#define RMAP_SCR_MODPISEL2              0
#define PAGE_SCR_MODPISEL2              2
#define RMAP_SCR_MODPISEL3              0
#define PAGE_SCR_MODPISEL3              2
#define RMAP_SCR_MODPISEL4              0
#define PAGE_SCR_MODPISEL4              2
#define RMAP_SCR_MODPISEL5              0
#define PAGE_SCR_MODPISEL5              2
#define RMAP_SCR_SCR_HWCFG              0
#define PAGE_SCR_SCR_HWCFG              2
#define RMAP_SCR_DBG_MODSUSP            0
#define PAGE_SCR_DBG_MODSUSP            2
#define RMAP_SCR_WCAN_DATA0_CTRL        0
#define PAGE_SCR_WCAN_DATA0_CTRL        3
#define RMAP_SCR_WCAN_DATA1_CTRL        0
#define PAGE_SCR_WCAN_DATA1_CTRL        3
#define RMAP_SCR_WCAN_DATA2_CTRL        0
#define PAGE_SCR_WCAN_DATA2_CTRL        3
#define RMAP_SCR_WCAN_DATA3_CTRL        0
#define PAGE_SCR_WCAN_DATA3_CTRL        3
#define RMAP_SCR_WCAN_DATA4_CTRL        0
#define PAGE_SCR_WCAN_DATA4_CTRL        3
#define RMAP_SCR_WCAN_DATA5_CTRL        0
#define PAGE_SCR_WCAN_DATA5_CTRL        3
#define RMAP_SCR_WCAN_DATA6_CTRL        0
#define PAGE_SCR_WCAN_DATA6_CTRL        3
#define RMAP_SCR_WCAN_DATA7_CTRL        0
#define PAGE_SCR_WCAN_DATA7_CTRL        3
#define RMAP_SCR_T2CCU_COCON            0
#define PAGE_SCR_T2CCU_COCON            3
#define RMAP_SCR_T2CCU_CC3L             0
#define PAGE_SCR_T2CCU_CC3L             3
#define RMAP_SCR_T2CCU_CC4L             0
#define PAGE_SCR_T2CCU_CC4L             3
#define RMAP_SCR_T2CCU_CC5L             0
#define PAGE_SCR_T2CCU_CC5L             3
#define RMAP_SCR_T2CCU_CC3H             0
#define PAGE_SCR_T2CCU_CC3H             3
#define RMAP_SCR_T2CCU_CC4H             0
#define PAGE_SCR_T2CCU_CC4H             3
#define RMAP_SCR_T2CCU_CC5H             0
#define PAGE_SCR_T2CCU_CC5H             3
#define RMAP_SCR_T2CCU_CCTDTCL          0
#define PAGE_SCR_T2CCU_CCTDTCL          4
#define RMAP_SCR_T2CCU_CCTDTCH          0
#define PAGE_SCR_T2CCU_CCTDTCH          4

#define SCR_ADCOMP_CON SFR(ADDR_SCR_ADCOMP_CON)

#endif /* _REGISTERS_H */
