/**********************************************************************************************************************
 * \file scr_adc_init.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "registers.h"
#include "scr_header_files.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void gpio_init(void){

    /* IO module configurations*/
       SCR_IO_PAGE = 2;        //Switch to page 2
       SCR_P00_PDISC = 0x00;
       SCR_P01_PDISC = 0x00;

       SCR_IO_PAGE = 1;        //Switch to page 1
       SCR_P00_IOCR3 = 0x80;
       SCR_P00_IOCR4 = 0x80;
       SCR_P00_IOCR5 = 0x80;
   //-----------------------------------------------------------------------------------
       SCR_IO_PAGE = 1;  // Switch IO PAGE 1
       SCR_P01_IOCR2 = 0x08;    // Configure P00.2 as Input and Input pull-down device connected -> PC = 0XX01
       SCR_IO_PAGE = 0;         // Switch IO PAGE 0

       SCR_IO_PAGE = 2;
       SCR_P00_PDISC  &= ~(1 << 2);
       SCR_P00_PDR2 |= 0x08;  // PAGE = 2;
       SCR_IO_PAGE = 0;


       // external Interrupt for P00.2 -> EXINT2 -> EX2IRQ Node and  EXINT5 -> EX5IRQ Node
       SCR_SCU_PAGE = 2;
       SCR_MODPISEL1 |= 0x00;// Bit 00 -> EXINT2A mit MUX gewählt,
       SCR_MODPISEL2 |= 0x00;// Bit 00 -> EXINT5A mit MUX gewählt,
       SCR_SCU_PAGE = 0;
       // fallende oder steigende flanken? 00 falling and 01 Rissing,  11 Disable
       SCR_SCU_PAGE = 1;
       SCR_EXICON0 = 0x0F; // Bit Name EXINT2 und Nummer [4-5]= 00 in Reg EXICON0 Node 8
       SCR_EXICON1 = 0xF4; // Bit Name EXINT5 und Nemmer [2-3]= 01 in Reg EXICON1 Node 9
       SCR_SCU_PAGE = 0;

   //PAGE: X  Bit 2 and 3
       SCR_IEN1 |= (1 << 2);    //enabled Interrupt Node 8
       SCR_IEN1 |= (1 << 3);    //enabled Interrupt Node 9

}














